/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package github.com.timohirt.bowling_game;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        var game = new Game();

        Arrays.asList(args).forEach(pinsHitString -> {
            var pinsHit = Integer.parseInt(pinsHitString);
            game.addRoll(pinsHit);
        });
        System.out.printf("Total score is: %d", game.currentScore().getValue());
    }
}
